# 端口号
server.port: 8083
# 定义服务名
spring.application.name: feign-consumer
# 定义注册中心地址
eureka.client:
  serviceUrl.defaultZone: http://localhost:8081/eureka/
#  register-with-eureka: false #开启Zuul面向服务路由需要开启服务注册

# 开启Feign客户端Hystrix熔断
feign.hystrix.enabled: true


# Ribbon全局配置
ribbon:
  ConnectTimeout: 250               #ribbon请求连接的超时时间
  ReadTimeout: 1000                 #请求处理的超时时间
  OkToRetryOnAllOperations: true    #对所有操作请求都进行重试
  MaxAutoRetries: 1                 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1       #对下个实例的重试次数

# Hystrix全局超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2000

# 全局日志配置
logging:
  level: debug