server:
  port: 8081  #指定端口号为8081 区分端口

spring:
  application:
    name: dubbo-rpc
  dubbo:
    application.name: consumer     #Dubbo服务名称
    registry.address: N/A          #禁用注册
    protocol:
      name: dubbo                  #使用Dubbo 自定义协议
      port: 20880                  #将Dubbo服务发布到20880端口
    scan: org.ko.rpc               #自动扫描Dubbo自定注解