server.port: 1337

spring:
  application.name: ko-generator
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    ip: 111.231.224.68
    port: 3306
    name: art-prototype
    username: root
    password: tiger
    url: jdbc:mysql://${spring.datasource.ip}:${spring.datasource.port}/${spring.datasource.name}?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false

# 生成工具配置
ko.generator:
  moduleName: springboot-rest
  tables: art_plan
  java:
    rootPackage: org.ko.api
    mybatis:
      domain: entity
      mapper: dao
      xml: mappers
  view:
    path: d://
    js: js
    html: module
  generator:
    project:
      enable: false
      name: ko
      path: d://

