package org.ko.api.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ko.api.entity.Plan;
import org.ko.api.entity.PlanExample;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    long countByExample(PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    int deleteByExample(PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    int insertSelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    List<Plan> selectByExampleWithRowbounds(PlanExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    List<Plan> selectByExample(PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    Plan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") Plan record, @Param("example") PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    int updateByExample(@Param("record") Plan record, @Param("example") PlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    int updateByPrimaryKeySelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_plan
     *
     * @mbg.generated Sat Mar 31 16:47:24 CST 2018
     */
    int updateByPrimaryKey(Plan record);
}