drop table country if exists;

create table country (
  id int primary key auto_increment,
  country_name varchar(32),
  country_code varchar(2)
);

insert into country (id, country_name, country_code) values(1,'Angola','AO');
insert into country (id, country_name, country_code) values(2,'Afghanistan','AF');
insert into country (id, country_name, country_code) values(3,'Albania','AL');
insert into country (id, country_name, country_code) values(4,'Algeria','DZ');
insert into country (id, country_name, country_code) values(5,'Andorra','AD');
insert into country (id, country_name, country_code) values(6,'Anguilla','AI');
insert into country (id, country_name, country_code) values(7,'Antigua and Barbuda','AG');
insert into country (id, country_name, country_code) values(8,'Argentina','AR');
insert into country (id, country_name, country_code) values(9,'Armenia','AM');
insert into country (id, country_name, country_code) values(10,'Australia','AU');
insert into country (id, country_name, country_code) values(11,'Austria','AT');
insert into country (id, country_name, country_code) values(12,'Azerbaijan','AZ');
insert into country (id, country_name, country_code) values(13,'Bahamas','BS');
insert into country (id, country_name, country_code) values(14,'Bahrain','BH');
insert into country (id, country_name, country_code) values(15,'Bangladesh','BD');
insert into country (id, country_name, country_code) values(16,'Barbados','BB');
insert into country (id, country_name, country_code) values(17,'Belarus','BY');
insert into country (id, country_name, country_code) values(18,'Belgium','BE');
insert into country (id, country_name, country_code) values(19,'Belize','BZ');
insert into country (id, country_name, country_code) values(20,'Benin','BJ');
insert into country (id, country_name, country_code) values(21,'Bermuda Is.','BM');
insert into country (id, country_name, country_code) values(22,'Bolivia','BO');
insert into country (id, country_name, country_code) values(23,'Botswana','BW');
insert into country (id, country_name, country_code) values(24,'Brazil','BR');
insert into country (id, country_name, country_code) values(25,'Brunei','BN');
insert into country (id, country_name, country_code) values(26,'Bulgaria','BG');
insert into country (id, country_name, country_code) values(27,'Burkina-faso','BF');
insert into country (id, country_name, country_code) values(28,'Burma','MM');
insert into country (id, country_name, country_code) values(29,'Burundi','BI');
insert into country (id, country_name, country_code) values(30,'Cameroon','CM');
insert into country (id, country_name, country_code) values(31,'Canada','CA');
insert into country (id, country_name, country_code) values(32,'Central African Republic','CF');
insert into country (id, country_name, country_code) values(33,'Chad','TD');
insert into country (id, country_name, country_code) values(34,'Chile','CL');
insert into country (id, country_name, country_code) values(35,'China','CN');
insert into country (id, country_name, country_code) values(36,'Colombia','CO');
insert into country (id, country_name, country_code) values(37,'Congo','CG');
insert into country (id, country_name, country_code) values(38,'Cook Is.','CK');
insert into country (id, country_name, country_code) values(39,'Costa Rica','CR');
insert into country (id, country_name, country_code) values(40,'Cuba','CU');
insert into country (id, country_name, country_code) values(41,'Cyprus','CY');
insert into country (id, country_name, country_code) values(42,'Czech Republic','CZ');
insert into country (id, country_name, country_code) values(43,'Denmark','DK');
insert into country (id, country_name, country_code) values(44,'Djibouti','DJ');
insert into country (id, country_name, country_code) values(45,'Dominica Rep.','DO');
insert into country (id, country_name, country_code) values(46,'Ecuador','EC');
insert into country (id, country_name, country_code) values(47,'Egypt','EG');
insert into country (id, country_name, country_code) values(48,'EI Salvador','SV');
insert into country (id, country_name, country_code) values(49,'Estonia','EE');
insert into country (id, country_name, country_code) values(50,'Ethiopia','ET');
insert into country (id, country_name, country_code) values(51,'Fiji','FJ');
insert into country (id, country_name, country_code) values(52,'Finland','FI');
insert into country (id, country_name, country_code) values(53,'France','FR');
insert into country (id, country_name, country_code) values(54,'French Guiana','GF');
insert into country (id, country_name, country_code) values(55,'Gabon','GA');
insert into country (id, country_name, country_code) values(56,'Gambia','GM');
insert into country (id, country_name, country_code) values(57,'Georgia','GE');
insert into country (id, country_name, country_code) values(58,'Germany','DE');
insert into country (id, country_name, country_code) values(59,'Ghana','GH');
insert into country (id, country_name, country_code) values(60,'Gibraltar','GI');
insert into country (id, country_name, country_code) values(61,'Greece','GR');
insert into country (id, country_name, country_code) values(62,'Grenada','GD');
insert into country (id, country_name, country_code) values(63,'Guam','GU');
insert into country (id, country_name, country_code) values(64,'Guatemala','GT');
insert into country (id, country_name, country_code) values(65,'Guinea','GN');
insert into country (id, country_name, country_code) values(66,'Guyana','GY');
insert into country (id, country_name, country_code) values(67,'Haiti','HT');
insert into country (id, country_name, country_code) values(68,'Honduras','HN');
insert into country (id, country_name, country_code) values(69,'Hongkong','HK');
insert into country (id, country_name, country_code) values(70,'Hungary','HU');
insert into country (id, country_name, country_code) values(71,'Iceland','IS');
insert into country (id, country_name, country_code) values(72,'India','IN');
insert into country (id, country_name, country_code) values(73,'Indonesia','ID');
insert into country (id, country_name, country_code) values(74,'Iran','IR');
insert into country (id, country_name, country_code) values(75,'Iraq','IQ');
insert into country (id, country_name, country_code) values(76,'Ireland','IE');
insert into country (id, country_name, country_code) values(77,'Israel','IL');
insert into country (id, country_name, country_code) values(78,'Italy','IT');
insert into country (id, country_name, country_code) values(79,'Jamaica','JM');
insert into country (id, country_name, country_code) values(80,'Japan','JP');
insert into country (id, country_name, country_code) values(81,'Jordan','JO');
insert into country (id, country_name, country_code) values(82,'Kampuchea (Cambodia )','KH');
insert into country (id, country_name, country_code) values(83,'Kazakstan','KZ');
insert into country (id, country_name, country_code) values(84,'Kenya','KE');
insert into country (id, country_name, country_code) values(85,'Korea','KR');
insert into country (id, country_name, country_code) values(86,'Kuwait','KW');
insert into country (id, country_name, country_code) values(87,'Kyrgyzstan','KG');
insert into country (id, country_name, country_code) values(88,'Laos','LA');
insert into country (id, country_name, country_code) values(89,'Latvia','LV');
insert into country (id, country_name, country_code) values(90,'Lebanon','LB');
insert into country (id, country_name, country_code) values(91,'Lesotho','LS');
insert into country (id, country_name, country_code) values(92,'Liberia','LR');
insert into country (id, country_name, country_code) values(93,'Libya','LY');
insert into country (id, country_name, country_code) values(94,'Liechtenstein','LI');
insert into country (id, country_name, country_code) values(95,'Lithuania','LT');
insert into country (id, country_name, country_code) values(96,'Luxembourg','LU');
insert into country (id, country_name, country_code) values(97,'Macao','MO');
insert into country (id, country_name, country_code) values(98,'Madagascar','MG');
insert into country (id, country_name, country_code) values(99,'Malawi','MW');
insert into country (id, country_name, country_code) values(100,'Malaysia','MY');
insert into country (id, country_name, country_code) values(101,'Maldives','MV');
insert into country (id, country_name, country_code) values(102,'Mali','ML');
insert into country (id, country_name, country_code) values(103,'Malta','MT');
insert into country (id, country_name, country_code) values(104,'Mauritius','MU');
insert into country (id, country_name, country_code) values(105,'Mexico','MX');
insert into country (id, country_name, country_code) values(106,'Moldova, Republic of','MD');
insert into country (id, country_name, country_code) values(107,'Monaco','MC');
insert into country (id, country_name, country_code) values(108,'Mongolia','MN');
insert into country (id, country_name, country_code) values(109,'Montserrat Is','MS');
insert into country (id, country_name, country_code) values(110,'Morocco','MA');
insert into country (id, country_name, country_code) values(111,'Mozambique','MZ');
insert into country (id, country_name, country_code) values(112,'Namibia','NA');
insert into country (id, country_name, country_code) values(113,'Nauru','NR');
insert into country (id, country_name, country_code) values(114,'Nepal','NP');
insert into country (id, country_name, country_code) values(115,'Netherlands','NL');
insert into country (id, country_name, country_code) values(116,'New Zealand','NZ');
insert into country (id, country_name, country_code) values(117,'Nicaragua','NI');
insert into country (id, country_name, country_code) values(118,'Niger','NE');
insert into country (id, country_name, country_code) values(119,'Nigeria','NG');
insert into country (id, country_name, country_code) values(120,'North Korea','KP');
insert into country (id, country_name, country_code) values(121,'Norway','NO');
insert into country (id, country_name, country_code) values(122,'Oman','OM');
insert into country (id, country_name, country_code) values(123,'Pakistan','PK');
insert into country (id, country_name, country_code) values(124,'Panama','PA');
insert into country (id, country_name, country_code) values(125,'Papua New Cuinea','PG');
insert into country (id, country_name, country_code) values(126,'Paraguay','PY');
insert into country (id, country_name, country_code) values(127,'Peru','PE');
insert into country (id, country_name, country_code) values(128,'Philippines','PH');
insert into country (id, country_name, country_code) values(129,'Poland','PL');
insert into country (id, country_name, country_code) values(130,'French Polynesia','PF');
insert into country (id, country_name, country_code) values(131,'Portugal','PT');
insert into country (id, country_name, country_code) values(132,'Puerto Rico','PR');
insert into country (id, country_name, country_code) values(133,'Qatar','QA');
insert into country (id, country_name, country_code) values(134,'Romania','RO');
insert into country (id, country_name, country_code) values(135,'Russia','RU');
insert into country (id, country_name, country_code) values(136,'Saint Lueia','LC');
insert into country (id, country_name, country_code) values(137,'Saint Vincent','VC');
insert into country (id, country_name, country_code) values(138,'San Marino','SM');
insert into country (id, country_name, country_code) values(139,'Sao Tome and Principe','ST');
insert into country (id, country_name, country_code) values(140,'Saudi Arabia','SA');
insert into country (id, country_name, country_code) values(141,'Senegal','SN');
insert into country (id, country_name, country_code) values(142,'Seychelles','SC');
insert into country (id, country_name, country_code) values(143,'Sierra Leone','SL');
insert into country (id, country_name, country_code) values(144,'Singapore','SG');
insert into country (id, country_name, country_code) values(145,'Slovakia','SK');
insert into country (id, country_name, country_code) values(146,'Slovenia','SI');
insert into country (id, country_name, country_code) values(147,'Solomon Is','SB');
insert into country (id, country_name, country_code) values(148,'Somali','SO');
insert into country (id, country_name, country_code) values(149,'South Africa','ZA');
insert into country (id, country_name, country_code) values(150,'Spain','ES');
insert into country (id, country_name, country_code) values(151,'Sri Lanka','LK');
insert into country (id, country_name, country_code) values(152,'St.Lucia','LC');
insert into country (id, country_name, country_code) values(153,'St.Vincent','VC');
insert into country (id, country_name, country_code) values(154,'Sudan','SD');
insert into country (id, country_name, country_code) values(155,'Suriname','SR');
insert into country (id, country_name, country_code) values(156,'Swaziland','SZ');
insert into country (id, country_name, country_code) values(157,'Sweden','SE');
insert into country (id, country_name, country_code) values(158,'Switzerland','CH');
insert into country (id, country_name, country_code) values(159,'Syria','SY');
insert into country (id, country_name, country_code) values(160,'Taiwan','TW');
insert into country (id, country_name, country_code) values(161,'Tajikstan','TJ');
insert into country (id, country_name, country_code) values(162,'Tanzania','TZ');
insert into country (id, country_name, country_code) values(163,'Thailand','TH');
insert into country (id, country_name, country_code) values(164,'Togo','TG');
insert into country (id, country_name, country_code) values(165,'Tonga','TO');
insert into country (id, country_name, country_code) values(166,'Trinidad and Tobago','TT');
insert into country (id, country_name, country_code) values(167,'Tunisia','TN');
insert into country (id, country_name, country_code) values(168,'Turkey','TR');
insert into country (id, country_name, country_code) values(169,'Turkmenistan','TM');
insert into country (id, country_name, country_code) values(170,'Uganda','UG');
insert into country (id, country_name, country_code) values(171,'Ukraine','UA');
insert into country (id, country_name, country_code) values(172,'United Arab Emirates','AE');
insert into country (id, country_name, country_code) values(173,'United Kiongdom','GB');
insert into country (id, country_name, country_code) values(174,'United States of America','US');
insert into country (id, country_name, country_code) values(175,'Uruguay','UY');
insert into country (id, country_name, country_code) values(176,'Uzbekistan','UZ');
insert into country (id, country_name, country_code) values(177,'Venezuela','VE');
insert into country (id, country_name, country_code) values(178,'Vietnam','VN');
insert into country (id, country_name, country_code) values(179,'Yemen','YE');
insert into country (id, country_name, country_code) values(180,'Yugoslavia','YU');
insert into country (id, country_name, country_code) values(181,'Zimbabwe','ZW');
insert into country (id, country_name, country_code) values(182,'Zaire','ZR');
insert into country (id, country_name, country_code) values(183,'Zambia','ZM');