spring:
  application:
    name: spring-boot #spring boot 快速启动
  datasource:
    url: jdbc:mysql://localhost:3306/artist     #数据库URL
    username: ko                                #数据库登录名
    password: tiger                             #数据库登录密码
    driver-class-name: com.mysql.jdbc.Driver    #数据库驱动

server:
  session:
    timeout: 3600 #session 超时时间 (秒)
  port: 8080  #端口号
