spring:
  application:
    name: user-edge-service
  redis:
    host: 192.168.1.7
    port: 6379
    password: tiger
    timeout: 30000
server:
  port: 8082

thrift:
  user:
    ip: 127.0.0.1
    port: 7911
  message:
    ip: 127.0.0.1
    port: 9090
