spring:
  datasource:
    url: jdbc:h2:mem:jwt-demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    open-in-view: false
  datasource.platform: h2
  h2.console:
    settings.web-allow-others: true
    enabled: true


